import api from '../api/axios';

/**
 * Print any content with company header and footer
 * @param {string} content - HTML string to print
 * @param {object} options - { title, landscape }
 */
export const printContent = async (content, options = {}) => {
  let company = { name: 'HDM ERP', address: '', phone: '', email: '' };
  let footerText = '';

  // Fetch company info and settings
  try {
    const [companyRes, landingRes] = await Promise.all([
      api.get('/tenant/company'),
      api.get('/public/landing')
    ]);
    const c = companyRes.data.data || {};
    company = {
      name: c.companyName || 'HDM ERP',
      address: c.address ? `${c.address.street || ''} ${c.address.city || ''} ${c.address.country || ''}`.trim() : '',
      phone: c.contactPhone || '',
      email: c.contactEmail || ''
    };
    footerText = landingRes.data.data?.footer?.copyright || '';
  } catch {}

  const now = new Date();
  const dateStr = now.toLocaleDateString('en-KE', { day: '2-digit', month: 'short', year: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-KE', { hour: '2-digit', minute: '2-digit' });

  const printWindow = window.open('', '_blank', 'width=900,height=700');
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${options.title || 'Print'}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; color: #111; padding: 20px; }
        .header { text-align: center; margin-bottom: 20px; padding-bottom: 10px; border-bottom: 1px solid #10B981; }
        .header h1 { font-size: 18px; color: #10B981; margin-bottom: 2px; }
        .header p { font-size: 10px; color: #555; margin: 1px 0; }
        .content { margin-bottom: 30px; }
        .footer { text-align: center; margin-top: 30px; padding-top: 8px; border-top: 0.5px solid #ccc; font-size: 9px; color: #888; }
        .footer .brand { color: #10B981; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 6px 8px; text-align: left; border-bottom: 1px solid #eee; }
        th { background: #f5f5f5; font-weight: 600; }
        @media print { body { padding: 10px; } }
        ${options.landscape ? '@page { size: landscape; }' : ''}
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${company.name}</h1>
        ${company.address ? `<p>${company.address}</p>` : ''}
        ${company.phone || company.email ? `<p>${[company.phone, company.email].filter(Boolean).join(' • ')}</p>` : ''}
      </div>
      <div class="content">${content}</div>
      <div class="footer">
        ${footerText ? `<p>${footerText}</p>` : ''}
        <p>Generated by <span class="brand">HDM ERP</span> at ${dateStr} ${timeStr}</p>
      </div>
      <script>
        window.onload = function() { window.print(); window.onafterprint = function() { window.close(); }; };
      </script>
    </body>
    </html>
  `);
  printWindow.document.close();
};

/**
 * Print a table from array data
 * @param {Array} data - Array of objects
 * @param {Array} columns - [{ key, label }]
 * @param {object} options - { title }
 */
export const printTable = async (data, columns, options = {}) => {
  const headerRow = columns.map(c => `<th>${c.label}</th>`).join('');
  const bodyRows = data.map(row => {
    const cells = columns.map(c => `<td>${row[c.key] ?? ''}</td>`).join('');
    return `<tr>${cells}</tr>`;
  }).join('');

  const content = `
    <h2 style="margin-bottom:10px;font-size:14px;">${options.title || ''}</h2>
    <table><thead><tr>${headerRow}</tr></thead><tbody>${bodyRows}</tbody></table>
  `;

  await printContent(content, options);
};

/**
 * Print a single record detail
 * @param {object} record - Key-value pairs
 * @param {object} options - { title }
 */
export const printDetail = async (record, options = {}) => {
  const rows = Object.entries(record)
    .map(([key, value]) => `
      <div style="display:flex;padding:4px 0;border-bottom:1px solid #eee;">
        <strong style="width:160px;text-transform:capitalize;">${key.replace(/([A-Z])/g, ' $1')}</strong>
        <span>${value ?? ''}</span>
      </div>
    `).join('');

  const content = `
    <h2 style="margin-bottom:10px;font-size:14px;">${options.title || ''}</h2>
    ${rows}
  `;

  await printContent(content, options);
};

export default { printContent, printTable, printDetail };